# This is a basic workflow to help you get started with Actions

name: CI Test 0

## Controls when the workflow will run
on:
#  # Triggers the workflow on push or pull request events but only for the main branch
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!

  log:
    runs-on: ubuntu-latest
    needs: [ build, test ]
    steps:
      - uses: actions/checkout@v2
#      - uses: actions/cache@v1
      - name: Run a one-line script
        run: |
          echo "Log level: ${{ github.event.inputs.logLevel }}"
